monitor/urls.py
from django.urls import path
from . import views

app_name = 'monitor'

urlpatterns = [
    path('login_records/', views.login_records, name='login_records'),
    path('add_movie/', views.add_movie, name='add_movie'),
    path('comment_records/', views.comment_records, name='comment_records'),
]

movierec/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from user import urls

urlpatterns = [
    path('admin', admin.site.urls),
    url('user/', include('user.urls')),
    url('movies/', include('movies.urls')),
    url('rec/', include('rec.urls')),
    url('rating/', include('rating.urls')),
    url('portrait/', include('portrait.urls')),
    url('monitor/', include('monitor.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('movie_detail/<int:movie_id>/', views.movie_detail, name='movie_detail'),
    path('search/', views.search, name='search'),
    path('rate/<int:movie_id>/', views.rate, name='rate'),
]

portrait/urls.py
from django.urls import path
from . import views

app_name = 'portrait'

urlpatterns = [
    path('analyse/', views.analyse, name='analyse'),
]

rating/urls.py
from django.urls import path
from . import views

app_name = 'rating'

urlpatterns = [
    path('rating/', views.rating, name='rating'),
]

rec/urls.py
from django.urls import path
from . import views

app_name = 'rec'

urlpatterns = [
    path('recommendations/', views.recommendations, name='recommendations'),
    path('IBUCF/', views.IBUCF, name='IBUCF'),
    path('IBICF/', views.IBICF, name='IBICF'),
]

user/urls.py
from django.urls import path
from api.views import user_list
from .views import register, login_view, home, profile, logout_view, favourite
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('home/', home, name='home'),
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('api/user_list/', user_list, name='user_list'),
    path('profile/', profile, name='profile'),
    path('logout/', logout_view, name='logout'),
    path('favouriate/', favourite, name='favourite'),
]

user/models.py
import numpy as np
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
import csv


class MyUserManager(BaseUserManager):
    def create_user(self, username, email, password=None, label=''):
        if not username:
            raise ValueError('Users must have a valid username.')

        if not email:
            raise ValueError('Users must have a valid email address.')

        user = self.model(
            username=username,
            email=self.normalize_email(email),
            label=label
        )

        user.set_password(password)
        user.save()

        return user

    def create_superuser(self, username, email, password):
        user = self.create_user(
            username=username,
            email=email,
            password=password
        )

        user.is_superuser = True
        user.is_staff = True
        user.save()

        return user


class MyUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=30, unique=True)
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(null=True)
    label = models.CharField(max_length=255, blank=True, null=True)

    objects = MyUserManager()

    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'

    def set_label(self, label):
        self.label = label
        return self

    def __str__(self):
        return self.username


def similarity(u, v):
    """
    计算余弦相似度
    :param u: 用户u的评分向量
    :param v: 用户v的评分向量
    :return: 用户u和用户v的余弦相似度
    """
    return np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))

user/views.py
from django.contrib.auth.hashers import check_password
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
import datetime
from monitor.models import LoginRecord
from .models import MyUser
from rec.rec import update_ml_movies


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        # Check if passwords match
        if password1 != password2:
            error_message = 'Passwords do not match'
            return render(request, 'registration/register.html', {'error_message': error_message})

        # Check if username already exists
        if MyUser.objects.filter(username=username).exists():
            error_message = 'username already exists'
            return render(request, 'registration/register.html', {'error_message': error_message})

        # Create the user
        user = MyUser.objects.create_user(username=username, email=email, password=password1)
        user.save()

        # Log the user in and redirect to home page
        login(request, user)
        return render(request, 'registration/profile.html')

    return render(request, 'registration/register.html')


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        try:
            user = MyUser.objects.get(username=username)
            if check_password(password, user.password):
                login(request, user)
                login_record = LoginRecord(username=user.username, login_time=datetime.datetime.now())
                login_record.save()
                if user.is_staff:
                    return redirect('monitor:add_movie')  # Replace with the URL name for the monitor's page
                else:
                    return redirect('user:profile')
            else:
                error_message = 'Invalid password'
                return render(request, 'registration/login.html', {'error_message': error_message})
        except MyUser.DoesNotExist:
            error_message = 'User does not exist'
            return render(request, 'registration/login.html', {'error_message': error_message})
    return render(request, 'registration/login.html')


def profile(request):
    update_ml_movies()
    return render(request, 'registration/profile.html')


def home(request):
    return render(request, 'registration/home.html')


def my_view(request):
    if request.method == 'POST' and 'logout' in request.POST:
        logout(request)
        return redirect('registration/logout.html')
    elif request.method == 'GET' and request.GET.get('logout'):
        logout(request)
        return redirect('registration/logout.html')


def logout_view(request):
    logout(request)
    return render(request, 'registration/logout.html')


def favourite(request):
    genres = ["爱情", "传记", "动画", "动作", "短片", "儿童", "犯罪", "歌舞", "古装", "纪录片", "家庭", "惊悚", "剧情", "科幻", "恐怖", "历史", "冒险",
              "奇幻", "脱口秀", "武侠", "舞台艺术", "西部", "喜剧", "悬疑", "音乐", "运动", "战争", "真人秀", "黑色电影", "情色", "同性", "灾难", "戏曲"]

    if request.method == 'POST':
        user = MyUser.objects.get(username=request.user.username)
        value_list = request.POST.getlist("movie_type", [])
        print(user.username)
        res = ""
        for i in value_list:
            res += i
            res += " "
        print(res)
        user.label = res
        user.save()
        return render(request, 'registration/favourite.html', {"select_value": value_list, "genres": genres})

    return render(request, 'registration/favourite.html', {"genres": genres})

user/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'user:home' %}">My Site</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    {% if user.is_authenticated and not user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:profile' %}">Profile</a>
                    </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:favourite' %}">favourite</a>
                    </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'rating:rating' %}">rating</a>
                    </li>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'rec:recommendations' %}">recommendations</a>
                    </li>
                        </li>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'rec:IBUCF' %}">IBUCF</a>
                    </li>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'rec:IBICF' %}">IBICF</a>
                    </li>
                        </li>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'portrait:analyse' %}">analyse</a>
                    </li>
                        <form class="d-flex mx-4 my-auto" action="{% url 'movies:search' %}" method="get">
    <input class="form-control me-2" type="search" name="query" placeholder="Search Movies" aria-label="Search Movies">
    <button class="btn btn-outline-success" type="submit">Search</button>
</form>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:logout' %}?next=/user/logout.html">Logout</a>
                    </li>
                        {% elif user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'monitor:add_movie' %}">Add Movie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'monitor:login_records' %}">login records</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'monitor:login_records' %}">review records</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'monitor:comment_records' %}">comment records</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:logout' %}?next=/user/logout.html">Logout</a>
                    </li>
                        {% endif %}

                    {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:register' %}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
</body>
</html>