movierec/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from user import urls

urlpatterns = [
    path('admin', admin.site.urls),
    url('user/', include('user.urls')),
    url('movies/', include('movies.urls')),
    url('rec/', include('rec.urls')),
    url('rating/', include('rating.urls')),
    url('portrait/', include('portrait.urls')),
    url('monitor/', include('monitor.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('movie_detail/<int:movie_id>/', views.movie_detail, name='movie_detail'),
    path('search/', views.search, name='search'),
    path('rate/<int:movie_id>/', views.rate, name='rate'),
]

rec/urls.py
from django.urls import path
from . import views

app_name = 'rec'

urlpatterns = [
    path('recommendations/', views.recommendations, name='recommendations'),
    path('IBUCF/', views.IBUCF, name='IBUCF'),
    path('IBICF/', views.IBICF, name='IBICF'),
]

movies/models.py
import numpy as np
from django.db import models
from user.models import MyUser


class Movie(models.Model):
    title = models.CharField(max_length=255)
    english_title = models.CharField(max_length=255)
    director = models.CharField(max_length=255)
    writer = models.CharField(max_length=255)
    actors = models.CharField(max_length=50)
    rating = models.FloatField()
    tag1 = models.CharField(max_length=50)
    tag2 = models.CharField(max_length=50)
    tag3 = models.CharField(max_length=50)
    country = models.CharField(max_length=255)
    language = models.CharField(max_length=255)
    date = models.DateField()
    introduction = models.TextField()
    dataId = models.CharField(max_length=255,unique=True)
    url = models.CharField(max_length=255)
    pic = models.ImageField(upload_to='movie_images/', null=True, blank=True)


class UserHistory(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)


class UserLike(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)


def similarity(u, v):
    """
    计算余弦相似度
    :param u: 用户u的评分向量
    :param v: 用户v的评分向量
    :return: 用户u和用户v的余弦相似度
    """
    return np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))

movies/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from comment.forms import CommentForm
from comment.models import Comment
from user.models import MyUser
from .models import Movie
from rating.models import score
from django.core.cache import cache
from django.db.models import OuterRef, Subquery
from rec.rec import update_ml_movies


@login_required
def movie_detail(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    user = request.user
    rate = score.objects.filter(username=user.username, movieDataId=movie.dataId).first()
    comments = Comment.objects.filter(movieDataId=movie.dataId).order_by('-created_at')
    form = CommentForm()

    context = {
        'movie': movie,
        'comments': comments,
        'form': form,
    }

    if rate:
        context['rating'] = rate.score
    else:
        context['show_rating_button'] = True

    if request.method == 'POST':
        user_score = request.POST.get('score')
        if user_score:
            user_score = int(user_score)
            if 0 < user_score <= 10:
                rating = score.objects.create(username=user.username, movieDataId=movie.dataId, score=user_score)
                context['rating'] = rating.score
                context['show_rating_button'] = False
            update_ml_movies()

        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.username = request.user.username
            comment.movieDataId = movie.dataId
            comment.save()
            return redirect('movies:movie_detail', movie_id=movie.id)

    return render(request, 'movie_detail.html', context)


def rate(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    user = request.user

    # 判断用户是否已经对电影评分过
    rating = score.objects.filter(movieDataId=movie.dataId, username=user.username)
    if rating.exists():
        # 如果已经评分，则显示用户评分
        user_score = rating[0].score
        message = f'You rated {movie.title} with a score of {user_score}.'
    else:
        # 如果没有评分，则显示评分选项
        user_score = None
        message = f'Rate {movie.title}:'

        if request.method == 'POST':
            user_score = int(request.POST.get('score'))
            # 保存评分到数据库
            rating = score(username=user.username, movieDataId=movie.dataId, score=user_score)
            rating.save()
            message = f'You rated {movie.title} with a score of {user_score}.'
    movie_dataId = movie.dataId
    cache_key = f'mean_score_{movie_dataId}'
    cache.delete(cache_key)
    context = {
        'movie': movie,
        'score': user_score,
        'message': message,
    }
    return render(request, 'movie_detail.html', context)


def search(request):
    query = request.GET.get('query')
    movies = Movie.objects.filter(title__icontains=query)
    context = {
        'movies': movies,
        'query': query
    }
    return render(request, 'search.html', context)

movies/templates/movie_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <img src="{{ movie.pic }}" alt="{{ movie.title }} Image" class="img-thumbnail">
      </div>
      <div class="col-lg-8">
        <h1>{{ movie.title }}</h1>
        <p>id: {{ movie.id }}</p>
        <p>导演: {{ movie.director }}</p>
        <p>主演:{{ movie.actors }}</p>
        <p>上映日期: {{ movie.date }}</p>
        <p>评分: {{ movie.rating }}</p>
        <p>标签: {{ movie.tag1 }}, {{ movie.tag2 }}, {{ movie.tag3 }}</p>
        <p>国家/地区: {{ movie.country }}</p>
        <p>语言: {{ movie.language }}</p>
        <p>简介: {{ movie.introduction }}</p>

        {% if rating %}
        <p>你对该电影的评分是：{{ rating }}</p>
        {% else %}
        <form method="POST" action="{% url 'movies:rate' movie.id %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="score">请给该电影打分（1-10）：</label>
            <input type="number" class="form-control" id="score" name="score" min="1" max="10" required>
            <input type="hidden" name="movie_id" value="{{ movie.dataId }}">
          </div>
          <input type="submit" class="btn btn-primary" value="提交">
        </form>
        {% endif %}
      {% for comment in comments %}
        <div class="card my-3">
            <div class="card-body">
            <h5 class="card-title">{{ comment.username }}</h5>
            <p class="card-text">{{ comment.content }}</p>
            <p class="card-text"><small class="text-muted">{{ comment.created_at|date:"F j, Y, P" }}</small></p>
            </div>
        </div>
        {% empty %}
            <p>No comments yet.</p>
      {% endfor %}
          {% if user.is_authenticated %}
            <form method="POST" action="">
                {% csrf_token %}
                <div class="form-group">
                 <label for="content">Add a comment:</label>
            <textarea class="form-control" id="content" name="content" rows="3" required>{{ form.content.value|default:'' }}</textarea>
            </div>
            <input type="submit" class="btn btn-primary" value="Submit">
                </form>
        {% else %}
  <p>You must be logged in to post a comment.</p>
{% endif %}
      </div>
    </div>
  </div>
{% endblock %}

movies/templates/search.html
{% extends 'base.html' %}

{% block title %}Search - My Site{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Search results for "{{ query }}"</h1>
        {% if movies %}
            <div class="row">
            {% for movie in movies %}
                <div class="col-md-4 mb-4">
                        <div class="card">
                            {% if movie.pic %}
                                <img src="{{ movie.pic }}" alt="{{ movie.title }} Image" class="img-thumbnail">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{ movie.title }}</h5>
                                <p class="card-text">{{ movie.english_title }}</p>
                                <p class="card-text">Director: {{ movie.director }}</p>
                                <p class="card-text">Rating: {{ movie.rating }}</p>
                                <a href="{% url 'movies:movie_detail' movie.id %}">{{ movie.title }}</a>
                            </div>
                        </div>
                    </div>
            {% endfor %}
            </div>
        {% else %}
            <p>No results found.</p>
        {% endif %}
    </div>
{% endblock %}