movierec/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from user import urls

urlpatterns = [
    path('admin', admin.site.urls),
    url('user/', include('user.urls')),
    url('movies/', include('movies.urls')),
    url('rec/', include('rec.urls')),
    url('rating/', include('rating.urls')),
    url('portrait/', include('portrait.urls')),
    url('monitor/', include('monitor.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('movie_detail/<int:movie_id>/', views.movie_detail, name='movie_detail'),
    path('search/', views.search, name='search'),
    path('rate/<int:movie_id>/', views.rate, name='rate'),
]

rec/urls.py
from django.urls import path
from . import views

app_name = 'rec'

urlpatterns = [
    path('recommendations/', views.recommendations, name='recommendations'),
    path('IBUCF/', views.IBUCF, name='IBUCF'),
    path('IBICF/', views.IBICF, name='IBICF'),
]

rec/views.py
from django.shortcuts import render
from movies.models import Movie
from .rec import BICF, BUCF, coldstart  # 导入你的推荐算法


def recommendations(request):
    user_username = request.user.username
    recommended_movie_dataIds = coldstart(user_username)  # 获取推荐电影的 ID 列表
    recommended_movie_dataIds = list(set(recommended_movie_dataIds))
    recommended_movies = Movie.objects.filter(dataId__in=recommended_movie_dataIds)

    return render(request, 'recommendations.html', {'recommended_movies': recommended_movies})


def IBUCF(request):
    user_username = request.user.username
    recommended_movie_dataIds = BUCF(user_username)  # 获取推荐电影的 ID 列表
    recommended_movie_dataIds = list(set(recommended_movie_dataIds))
    recommended_movies = Movie.objects.filter(dataId__in=recommended_movie_dataIds)

    return render(request, 'IBUCF.html', {'recommended_movies': recommended_movies})


def IBICF(request):
    user_username = request.user.username
    recommended_movie_dataIds = BICF(user_username)  # 获取推荐电影的 ID 列表
    recommended_movie_dataIds = list(set(recommended_movie_dataIds))
    recommended_movies = Movie.objects.filter(dataId__in=recommended_movie_dataIds)

    return render(request, 'IBICF.html', {'recommended_movies': recommended_movies})

rec/templates/IBICF.html
{% extends "base.html" %}

{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Recommended Movies based on IBICF</h1>
        <div class="row">
            {% for movie in recommended_movies %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        {% if movie.pic %}
                            <img src="{{ movie.pic }}" alt="{{ movie.title }} Image" class="img-thumbnail">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ movie.title }}</h5>
                            <p class="card-text">{{ movie.english_title }}</p>
                            <p class="card-text">Director: {{ movie.director }}</p>
                            <p class="card-text">Rating: {{ movie.rating }}</p>
                            <a href="{% url 'movies:movie_detail' movie.id %}">{{ movie.title }}</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

rec/templates/IBUCF.html
{% extends "base.html" %}

{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Recommended Movies based on IBUCF</h1>
        <div class="row">
            {% for movie in recommended_movies %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        {% if movie.pic %}
                            <img src="{{ movie.pic }}" alt="{{ movie.title }} Image" class="img-thumbnail">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ movie.title }}</h5>
                            <p class="card-text">{{ movie.english_title }}</p>
                            <p class="card-text">Director: {{ movie.director }}</p>
                            <p class="card-text">Rating: {{ movie.rating }}</p>
                            <a href="{% url 'movies:movie_detail' movie.id %}">{{ movie.title }}</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

rec/templates/recommendations.html
{% extends "base.html" %}

{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Recommended Movies based on coldstart</h1>
        <div class="row">
            {% for movie in recommended_movies %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        {% if movie.pic %}
                            <img src="{{ movie.pic }}" alt="{{ movie.title }} Image" class="img-thumbnail">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ movie.title }}</h5>
                            <p class="card-text">{{ movie.english_title }}</p>
                            <p class="card-text">Director: {{ movie.director }}</p>
                            <p class="card-text">Rating: {{ movie.rating }}</p>
                            <a href="{% url 'movies:movie_detail' movie.id %}">{{ movie.title }}</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}